name: aws-ecr-credential-provider
on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true 
      - name:  Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.25
      - name: Build binary
        shell: bash
        run: make ecr-credential-provider-linux-amd64 ecr-credential-provider-linux-arm64
      - name: Output ecr-credential-provider-linux-amd64
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: ecr-credential-provider-linux-amd64
          path: ecr-credential-provider-linux-amd64
          if-no-files-found: error
      - name: Output ecr-credential-provider-linux-arm64
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: ecr-credential-provider-linux-arm64
          path: ecr-credential-provider-linux-arm64
          if-no-files-found: error

  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true 
      - name:  Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.25
      - name: Download amd64 binaries
        uses: actions/download-artifact@v4
        with:
          name: ecr-credential-provider-linux-amd64 
      - name: Download arm64 binaries
        uses: actions/download-artifact@v4
        with:
          name: ecr-credential-provider-linux-arm64 

      - name: Prepare release tag
        id: prep
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.prep.outputs.tag }}
          name: Release ${{ steps.prep.outputs.tag }}
          draft: false
          files: |
            ecr-credential-provider-linux-arm64
            ecr-credential-provider-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # You don't need to add this in secrets it's by default.      
